Get route prices from quoter
propeller-heads/turbine-sdk pull request #17
Opened 2024-07-08 08:59 UTC by PierreMkt

instead of hardcoding pair prices

2024-07-08 09:18 UTC, michcio1234 approved these changes
Nice! Not sure I like the idea to put it in `quoters`, but I don't have a strong opinion, so we can keep it.

2024-07-08 14:54 UTC, michcio1234 requested changes
I will change it.

2024-07-08 14:54 UTC, michcio1234 commented on src/models.ts
> +    public pairPrice?: number;
That's a weird idea to put it here :P

2024-07-08 15:02 UTC, michcio1234 commented on src/solvers/uniswap/uniswapSolver.ts
> +     * @returns A promise that resolves to a list of quote mappings .
What does it mean? Mappings from what to what?

2024-07-10 08:27 UTC, carloszanella commented on src/solvers/uniswap/uniswapSolver.ts
> +const QUOTER_API_URL = "https://dev-api.propellerheads.xyz/v1/solver/turbine/quote/";
are we keeping this URL? does it work (is it public)?

2024-07-10 14:55 UTC, michcio1234 approved these changes

2024-07-10 14:55 UTC, michcio1234 commented on __tests__/testIntegration.test.ts
> +                expect(BigInt(maxQuote.sell_amount)).toBeLessThanOrEqual(
Why do we allow it to be **less**?

2024-07-10 14:55 UTC, michcio1234 commented on __tests__/testIntegration.test.ts
> +                expect(maxQuote.buy_amount).toBeDefined();
```suggestion
                expect(maxQuote.buy_amount).toBeDefined();
                expect(maxQuote.buy_amount).toBeGreaterThan(minQuote.buy_amount);
```

2024-07-10 14:55 UTC, michcio1234 commented on src/solvers/uniswap/models.ts
> +}
I don't mind having this, but sometimes interfaces are nicer (more concise):
```suggestion
export interface Quote {
    /** The token to sell */
    public sell_token: Address;
    /** The token to buy */
    public buy_token: Address;
    /** The minimum amount of the sell token the route must handle */
    public sell_amount: bigint;
    /** The maximum amount of the sell token the route must handle */
    public buy_amount: bigint;
}
```

2024-07-10 17:08 UTC, merged